{% set name = "lightglue" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cvg/LightGlue/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aeff53bce856f6ca8a9764ce4572237f28462554966bee02db4876ed9444b2fd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch
    - torchvision
    - numpy
    - opencv
    - matplotlib-base
    - kornia

test:
  imports:
    - lightglue
    - lightglue.utils

about:
  home: https://github.com/cvg/LightGlue
  license: Apache-2.0
  license_file: LICENSE
  summary: LightGlue is a deep neural network that matches sparse local features across image pairs.
  doc_url: https://github.com/cvg/LightGlue
  dev_url: https://github.com/cvg/LightGlue

extra:
  recipe-maintainers:
    - Tobias-Fischer
